let defaultCsvOptions: Types.csvOptions
let defaultJsonOptions: Types.jsonOptions
let defaultMarkdownOptions: Types.markdownOptions
let defaultHtmlOptions: Types.htmlOptions
let defaultLatexOptions: Types.latexOptions
let t: Types.t
let getCsvOptions: Types.t => Types.csvOptions
let getJsonOptions: Types.t => Types.jsonOptions
let getMarkdownOptions: Types.t => Types.markdownOptions
let getHtmlOptions: Types.t => Types.htmlOptions
let getLatexOptions: Types.t => Types.latexOptions
